variable "cidr_block" {}
variable "public_subnets_cidr" {}
variable "availability_zones" {}
variable "private_subnets_cidr" {}
variable "region" {}
variable "environment" {}
variable "service" {}
variable "ami" {}
variable "instance_type" {}
variable "associate_public_ip_address" {}
variable "key_name" {}
variable "size" {}